# Generated by Django 6.0.3 on 2026-04-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('disease_name', models.CharField(max_length=255)),
                ('confidence_score', models.IntegerField(default=0)),
                ('treatments', models.JSONField(default=list)),
                ('estimated_days_to_harvest', models.IntegerField(blank=True, null=True)),
                ('estimated_yield', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
