# Generated by Django 6.0.3 on 2026-04-16 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='confidence_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='estimated_yield',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='image',
            field=models.ImageField(upload_to='scans/'),
        ),
    ]
