# Generated by Django 6.0.3 on 2026-04-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_backend', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistory',
            name='reviewed_by',
        ),
    ]
