# Generated by Django 6.0.3 on 2026-04-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_backend', '0006_remove_scanhistory_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
