# Generated by Django 6.0.3 on 2026-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_backend', '0007_userprofile_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_credits',
            field=models.IntegerField(default=3),
        ),
    ]
